version: '3.9'
services:
  database:
    image: "mysql/mysql-server:5.7"
    environment:
      - MYSQL_ROOT_PASSWORD=UglyDuckling
      # - MYSQL_ROOT_HOST=%   # Allow root to connect from any host
      # Optional:
      - MYSQL_DATABASE=lportal
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --character-set-filesystem=utf8mb4 --max_allowed_packet=256M
    volumes:
      - type: bind
        source: ./database/docker-entrypoint-initdb.d
        target: /docker-entrypoint-initdb.d
  search:
    image: liferaycloud/elasticsearch:7.13.3-4.1.2
    environment:
      - LCP_PROJECT_ENVIRONMENT=local
      - LCP_SERVICE_SCALE=1
      - LCP_SERVICE_ID=search
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - discovery.type=single-node
      - cluster.routing.allocation.disk.threshold_enabled=false
  liferay-1:
    container_name: liferay-1
    build:
      context: ./liferay
      dockerfile: Dockerfile
    depends_on:
      - database
      - search
    environment:
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_DRIVER_UPPERCASEC_LASS_UPPERCASEN_AME=com.mysql.cj.jdbc.Driver
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_URL=jdbc:mysql://database/lportal?characterEncoding=UTF-8&dontTrackOpenResources=true&holdResultsOpenOverStatementClose=true&serverTimezone=GMT&useFastDateParsing=false&useUnicode=true&useSSL=false
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_USERNAME=user
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_PASSWORD=password
      - LIFERAY_CLUSTER_PERIOD_LINK_PERIOD_ENABLED=true
      - LIFERAY_CLUSTER_PERIOD_LINK_PERIOD_AUTODETECT_PERIOD_ADDRESS=database:3306
      - LIFERAY_DL_PERIOD_STORE_PERIOD_IMPL=com.liferay.portal.store.db.DBStore
      - LIFERAY_WEB_PERIOD_SERVER_PERIOD_DISPLAY_PERIOD_NODE=true
      - LIFERAY_DISABLE_TRIAL_LICENSE=true
    volumes:
      - type: bind
        source: ./liferay/mnt
        target: /mnt/liferay
    ports:
      - "8080:8080"
  liferay-2:
    container_name: liferay-2
    build:
      context: ./liferay
      dockerfile: Dockerfile
    depends_on:
      - database
      - search
      - liferay-1
    environment:
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_DRIVER_UPPERCASEC_LASS_UPPERCASEN_AME=com.mysql.cj.jdbc.Driver
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_URL=jdbc:mysql://database/lportal?characterEncoding=UTF-8&dontTrackOpenResources=true&holdResultsOpenOverStatementClose=true&serverTimezone=GMT&useFastDateParsing=false&useUnicode=true&useSSL=false
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_USERNAME=user
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_PASSWORD=password
      - LIFERAY_CLUSTER_PERIOD_LINK_PERIOD_ENABLED=true
      - LIFERAY_CLUSTER_PERIOD_LINK_PERIOD_AUTODETECT_PERIOD_ADDRESS=database:3306
      - LIFERAY_DL_PERIOD_STORE_PERIOD_IMPL=com.liferay.portal.store.db.DBStore
      - LIFERAY_WEB_PERIOD_SERVER_PERIOD_DISPLAY_PERIOD_NODE=true
      - LIFERAY_DISABLE_TRIAL_LICENSE=true
    volumes:
      - type: bind
        source: ./liferay/mnt
        target: /mnt/liferay
    ports:
      - "8081:8080"
